import '@/styles/globals.css'

import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: {
    template: '%s | Desapega Vendas',
    default: 'Desapega Vendas',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt">
      <body className={(roboto.className, 'bg-desapegaFundo text-black')}>
        {children}
      </body>
    </html>
  )
}
